#!/bin/sh -ex

sed -i "s|^bind .*$|bind 0.0.0.0|" /etc/redis/redis.conf
npm install -g redis-commander
useradd --system -m -s /bin/false nodejs
useradd --system -d /home/nodejs -G nodejs -s /bin/false redis-commander
chmod g+w /home/nodejs
chmod +x /etc/init.d/redis-commander
update-rc.d redis-commander defaults


