#!/bin/bash -e
# regenerate redis password & disable protected mode by default

. /etc/default/inithooks

PASS=$(mcookie)$(mcookie)$(mcookie)$(mcookie)$(mcookie)
sed -i "s/protected-mode yes|protected-mode no" /etc/redis/redis.conf
sed -ri "s/(# *)?requirepass .*./requirepass $PASS/" /etc/redis/redis.conf
sed -ri "s|--redis-password='.*'|--redis-password='$PASS'|" /etc/init.d/redis-commander
