#!/bin/bash -e

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . INITHOOKS_CONF

$INITHOOKS_PATH/bin/redis.py 

PASS=$(mcookie)$(mcookie)$(mcookie)$(mcookie)$(mcookie)
sed -i "s/protected-mode yes|protected-mode no" /etc/redis/redis.conf
sed -ri "s/(# )?requirepass .*./requirepass $PASS/" /etc/redis/redis.conf
sed -ri "s|--redis-password='.*'|--redis-password='$PASS'|" /etc/init.d/redis-commander
