#!/bin/bash -e

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . INITHOOKS_CONF

# ensure other values are set if APP_PASS is
if [ -n "$APP_PASS" ]; then
    if [ -z "$APP_IP_BIND" ]; then
        APP_IP_BIND="0.0.0.0"
    fi
    if [ -z "$APP_PROTECTED" ]; then
        APP_PROTECTED="no"
    fi
fi

$INITHOOKS_PATH/bin/redis.py --pass="$APP_PASS" --ip_bind="$APP_IP_BIND" --protected_mode="$APP_PROTECTED"
